server:
  port: 8080

spring:
  application:
    name: PODBooking
  datasource:
    url: jdbc:mysql://${MYSQL_URL:localhost}:${MYSQL_PORT:3308}/pod
    #    url: ${MYSQL_URL:jdbc:mysql://localhost:3307/uniclub}
    username: ${MYSQL_ADMIN_USER:root}
    password: ${MYSQL_ADMIN_PASS:sa123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    mongodb:
      uri: mongodb://localhost:27017/pod-booking
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 3MB
