server:
  port: 8080

spring:
  application:
    name: PODBooking

  data:
    mongodb:
      uri: mongodb://localhost:27017/pod-booking
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 3MB
